name: Release

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
            - name: Install CMS dependencies
              working-directory: CMS
              run: npm ci
            - name: Install FE dependencies
              working-directory: FE
              run: npm ci
            - name: Lint CMS
              working-directory: CMS
              run: npx eslint .
              continue-on-error: true
            - name: Lint FE
              working-directory: FE
              run: npx eslint .
              continue-on-error: true

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
            - name: Install CMS dependencies
              working-directory: CMS
              run: npm ci
            - name: Build CMS
              working-directory: CMS
              run: npm run build
            - name: Install FE dependencies
              working-directory: FE
              run: npm ci
            - name: Build FE
              working-directory: FE
              run: npm run build
              env:
                  SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
                  SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}

    release:
        name: Release
        needs: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
            - name: Install dependencies
              run: npm ci
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
